/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/layout/BackTop.vue')['default']
    BlgEditor: typeof import('./src/components/BlgEditor.vue')['default']
    HeaderMenuTabs: typeof import('./src/components/layout/HeaderMenuTabs.vue')['default']
    HeaderSiteName: typeof import('./src/components/layout/HeaderSiteName.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/views/Home.vue')['default']
    LoginModal: typeof import('./src/components/views/LoginModal.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NList: typeof import('naive-ui')['NList']
    NMenu: typeof import('naive-ui')['NMenu']
    NSelect: typeof import('naive-ui')['NSelect']
    NTreeSelect: typeof import('naive-ui')['NTreeSelect']
    QuestionBank: typeof import('./src/components/views/QuestionBank.vue')['default']
    QuestionBankList: typeof import('./src/components/views/QuestionBankList.vue')['default']
    QuestionBankSearch: typeof import('./src/components/views/QuestionBankSearch.vue')['default']
    QuestionSubmitRecord: typeof import('./src/components/views/QuestionSubmitRecord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    UserAvatar: typeof import('./src/components/layout/UserAvatar.vue')['default']
  }
}
